name: Generate Results

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - Wiki

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # volle Git-History, alle Branches verfügbar

      - name: List Scripts
        run: ls -R $GITHUB_WORKSPACE/.github/scripts

      - name: Run filetype scan
        run: python $GITHUB_WORKSPACE/.github/scripts/filetype_scan.py

      - name: Generate Markdown
        run: python $GITHUB_WORKSPACE/.github/scripts/markdown_generator.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Results/*.json FILETYPES.md
          git commit -m "Automatische Aktualisierung der Results und FILETYPES.md" || echo "Nothing to commit"
          git push
